#import "com_epic_framework_common_Ui_EpicFile.h"
#import "java_lang_String.h"
#import "com_epic_framework_common_util_exceptions_EpicNativeMethodMissingImplementation.h"
#import "org_xmlvm_iphone_CGContext.h"
#import "org_xmlvm_iphone_CGFont.h"
#import <CoreGraphics/CGFont.h>

// Automatically generated by xmlvm2obj. Do not edit!


#import "com_epic_framework_implementation_EpicFontImplementationNative.h"
#import "org_xmlvm_iphone_NSObject.h"


@implementation com_epic_framework_implementation_EpicFontImplementationNative;

// CGFontCreateFromName
+ (org_xmlvm_iphone_CGFont*) CGFontCreateFromName___java_lang_String 
  : (java_lang_String *) name
{
  CGFontRef font = CGFontCreateWithFontName((CFStringRef)name);
  NSLog(@"Font['%@'] = %p", name, font); 
  return [XMLVM_NIL2NULL(font) retain];
}

// CGContextSetFont
+ (void) CGContextSetFont___java_lang_Object_org_xmlvm_iphone_CGContext
  : (java_lang_Object *) fontObject
  : (org_xmlvm_iphone_CGContext*) context
{
  NSLog(@"Setting font: %p", fontObject);
  CGContextSetFont(context->context, fontObject);
}

// CGFontGetAscent
+ (int) CGFontGetAscent___java_lang_Object
  : (java_lang_Object *) fontObject
{
  return CGFontGetAscent(fontObject);
}

// CGFontGetUnitsPerEm
+ (int) CGFontGetUnitsPerEm___java_lang_Object
  : (java_lang_Object *) fontObject
{
  return CGFontGetUnitsPerEm(fontObject);
}

// CGFontGetDescent
+ (int) CGFontGetDescent___java_lang_Object
  : (java_lang_Object *) fontObject
{
  return CGFontGetDescent(fontObject);
}

// measureAdvance
+ (int) measureAdvance___java_lang_Object_java_lang_String
  : (java_lang_Object *) fontObject
  : (java_lang_String *) text
{
  return 0;
}

@end

