#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class com_epic_framework_implementation_EpicBitmapImplementationNative;
@class java_lang_Object;
@class java_lang_String;
@class com_epic_framework_common_util_exceptions_EpicNativeMethodMissingImplementation;
@class org_xmlvm_iphone_UIImage;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface com_epic_framework_implementation_EpicBitmapImplementationNative : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
- (void) __init_com_epic_framework_implementation_EpicBitmapImplementationNative__;
+ (org_xmlvm_iphone_UIImage*) resizeImage___org_xmlvm_iphone_UIImage_int_int :(org_xmlvm_iphone_UIImage*)n1 :(int)n2 :(int)n3;

@end

