#import "com_epic_framework_common_util_EpicFail.h"
#import "com_epic_framework_common_util_exceptions_EpicRuntimeException.h"
#import "org_xmlvm_iphone_UIImage.h"

// Automatically generated by xmlvm2obj. Do not edit!


#import "com_epic_framework_implementation_EpicImplementationNative.h"
#import "org_xmlvm_iphone_NSObject.h"


@implementation com_epic_framework_implementation_EpicImplementationNative;

+ (void) initialize
{
    if (strcmp(class_getName(self), "com_epic_framework_implementation_EpicImplementationNative") == 0) {
    }
}

- (id) init
{
    if (self = [super init]) {
    }
    return self;
}

- (void) dealloc
{
    if (strcmp(object_getClassName(self), "com_epic_framework_implementation_EpicImplementationNative") == 0) {
        [self dealloc__];
    }
    [super dealloc];
}

- (void) __init_com_epic_framework_implementation_EpicImplementationNative__
{
    XMLVMElem _r0;
    _r0.o = self;
    [_r0.o retain];
    [((java_lang_Object*) _r0.o) __init_java_lang_Object__];
    [_r0.o release];
    return;
}
+ (org_xmlvm_iphone_UIImage*) resizeImage___org_xmlvm_iphone_UIImage_int_int :(org_xmlvm_iphone_UIImage*)n1 :(int)n2 :(int)n3
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    XMLVMElem _r1;
    XMLVMElem _r2;
    XMLVMElem _r3;
    _r1.o = n1;
    _r2.i = n2;
    _r3.i = n3;
    _r0.o = JAVA_NULL;
    [_r1.o retain];
    _r0.o = [com_epic_framework_common_util_EpicFail not_implemented__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
  }
+ (void) setupDebugHandlers__
{
    id        _ex = JAVA_NULL;
    XMLVMElem _r0;
    _r0.o = JAVA_NULL;
    _r0.o = [com_epic_framework_common_util_EpicFail not_implemented__];
    [_ex release];
    _ex = _r0.o;
   _r0.o = JAVA_NULL;
    @throw _ex;
  }

@end

