#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class java_lang_String;
@class com_epic_framework_implementation_UniqueIdGenerator;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface com_epic_framework_implementation_UniqueIdGenerator : java_lang_Object
{

}

+ (java_lang_String*) getUniqueDeviceId__;

@end

