#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class java_lang_String;
@class com_epic_framework_common_util_exceptions_EpicNativeMethodMissingImplementation;
@class org_xmlvm_iphone_UIImage;
@class com_epic_framework_implementation_EpicCanvasImplementationNative;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface com_epic_framework_implementation_EpicCanvasImplementationNative : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
- (void) __init_com_epic_framework_implementation_EpicCanvasImplementationNative__;
+ (org_xmlvm_iphone_UIImage*) drawImage___org_xmlvm_iphone_UIImage_int_int :(org_xmlvm_iphone_UIImage*)n1 :(int)n2 :(int)n3;
+ (void) setCrop___java_lang_Object_int_int_int_int :(java_lang_Object*)n1 :(int)n2 :(int)n3 :(int)n4 :(int)n5;
+ (void) restoreContext___java_lang_Object :(java_lang_Object*)n1;

@end

