#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class java_lang_Object;
@class java_lang_String;
@class com_epic_framework_common_util_exceptions_EpicNativeMethodMissingImplementation;
@class com_epic_framework_implementation_EpicIOImplementationNative;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface com_epic_framework_implementation_EpicIOImplementationNative : java_lang_Object
{

}
+ (void) initialize;
- (id) init;
- (void) __init_com_epic_framework_implementation_EpicIOImplementationNative__;
+ (void) writeFile___java_lang_String_byte_ARRAYTYPE :(java_lang_String*)n1 :(XMLVMArray*)n2;
+ (XMLVMArray*) readFile___java_lang_String :(java_lang_String*)n1;

@end

