#import "xmlvm.h"
#import "java_lang_Object.h"

// For circular include:
@class com_epic_framework_implementation_EpicBitmapImplementationNative;
@class java_lang_Object;
@class java_lang_String;
@class com_epic_framework_common_util_exceptions_EpicNativeMethodMissingImplementation;
@class org_xmlvm_iphone_UIImage;
@class org_xmlvm_iphone_CGPoint;

// Automatically generated by xmlvm2obj. Do not edit!


	
@interface com_epic_framework_implementation_EpicBitmapImplementationNative : java_lang_Object
{

}

+ (org_xmlvm_iphone_UIImage*) resizeImage___org_xmlvm_iphone_UIImage_int_int
  : (org_xmlvm_iphone_UIImage *) src
  : (int) width
  : (int) height;


@end

