#import "com_epic_framework_common_Ui_EpicFile.h"
#import "java_lang_String.h"
#import "com_epic_framework_common_util_exceptions_EpicNativeMethodMissingImplementation.h"
#import "org_xmlvm_iphone_CGContext.h"
#import "org_xmlvm_iphone_CGFont.h"
#import <CoreGraphics/CGFont.h>

// Automatically generated by xmlvm2obj. Do not edit!


#import "com_epic_framework_implementation_EpicFontImplementationNative.h"
#import "org_xmlvm_iphone_NSObject.h"


@implementation com_epic_framework_implementation_EpicFontImplementationNative;

// UIFont
+ (java_lang_Object*) UIFont___java_lang_String_int
  : (java_lang_String *) name
  : (int) size
{
  UIFont *font = [UIFont fontWithName:name size: size];
  //NSLog(@"Font['%@'] = %p", name, font); 
  return [XMLVM_NIL2NULL(font) retain];
}

// UIFontWithSize
+ (java_lang_Object *) UIFontWithSize___java_lang_Object_int
  : (java_lang_Object *) fontObject
  : (int) size
{
  UIFont *font = (UIFont *)fontObject;
  UIFont *newFont = [font fontWithSize: (CGFloat)size];
  return [XMLVM_NIL2NULL(newFont) retain];
}

// measureAscent
+ (int) measureAscent___java_lang_Object
  : (java_lang_Object *) fontObject
{
  UIFont *font = (UIFont*)fontObject;
  CGFloat a = [font ascender];
  //NSLog(@"ascent = %f", a);
  return (int)a;
}

// measureDescent
+ (int) measureDescent___java_lang_Object
  : (java_lang_Object *) fontObject
{
  UIFont *font = (UIFont*)fontObject;
  CGFloat a = [font descender];
  //NSLog(@"descent = %f", a);
  return (int)a;
}

// measureAdvance
+ (int) measureAdvance___java_lang_Object_java_lang_String
  : (java_lang_Object *) fontObject
  : (java_lang_String *) text
{
  UIFont *font = (UIFont *)fontObject;
  CGSize sz = [text sizeWithFont: font];
  //NSLog(@"Measured text to %fx%f", sz.width, sz.height);
  return (int)sz.width;
}

@end

