#import "mylib.h"
#import "MyObject.h"

// For circular include:
@class MyObject;
@class Iq;
@class com_epic_framework_implementation_UniqueIdGenerator;

// Automatically generated by mylib2obj. Do not edit!


	
@interface com_epic_framework_implementation_UniqueIdGenerator : MyObject
{

}
+ (void) initialize;
- (id) init;
- (void) initMyWith_com_epic_framework_implementation_UniqueIdGeneratorx;
+ (Iq*) getUniqueDeviceIdx;

@end

