#import "mylib.h"
#import "MyObject.h"

// For circular include:
@class MyObject;
@class com_epic_framework_implementation_EpicImplementationNative;
@class MyUIImage;

// Automatically generated by mylib2obj. Do not edit!


	
@interface com_epic_framework_implementation_EpicImplementationNative

+ (MyUIImage*) resizeImagex_MyUIImageMwMw :(MyUIImage*)n1 :(int)n2 :(int)n3;

@end

