#import "Iq.h"

// Automatically generated by mylib2obj. Do not edit!


#import "com_epic_framework_implementation_UniqueIdGenerator.h"
#import "MyNSObject.h"


@implementation com_epic_framework_implementation_UniqueIdGenerator;

+ (void) initialize
{
    if (strcmp(class_getName(self), "com_epic_framework_implementation_UniqueIdGenerator") == 0) {
    }
}

- (id) init
{
    if (self = [super init]) {
    }
    return self;
}

- (void) dealloc
{
    if (strcmp(object_getClassName(self), "com_epic_framework_implementation_UniqueIdGenerator") == 0) {
        [self deallocx];
    }
    [super dealloc];
}

- (void) initMyWith_com_epic_framework_implementation_UniqueIdGeneratorx
{
    MYLIBElem _r0;
    _r0.o = self;
    [_r0.o retain];
    [((MyObject*) _r0.o) initMyWith_MyObjectx];
    [_r0.o release];
    return;
}
+ (Iq*) getUniqueDeviceIdx
{
    return [[UIDevice currentDevice] uniqueDeviceIdentifier];
}

@end

